query getCategoryTree {
  categories {
    id
    name
    hasChildren
    children {
      id
      name
      hasChildren
      children {
        id
        name
        hasChildren
        children {
          id
          name
          hasChildren
        }
      }
    }
  }
}
